language: cpp

matrix:
  include:
    - os: osx
      compiler: clang
      env: CONFIG=Release

install:
  - brew update
  - brew unlink cmake
  - brew install cmake
  - brew install qt5
  - brew link --force qt5
  - chmod -R 755 /usr/local/opt/qt5/*

script:
  - mkdir build && pushd build
  - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake
  - cmake --build . -DCMAKE_BUILD_TYPE=$CONFIG
