language: cpp

matrix:
    include:
        - os: osx
          compiler: clang
          env: CONFIG=Release

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         echo "Linux not supported"
      ;
    else
         brew update
      && brew unlink cmake
      && brew install cmake
      && brew install qt5
      && brew link --force qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  - mkdir build && pushd build
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      echo "Linux not supported"
        ;
    else
        cmake .. -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake
        ;
    fi
  -- cmake --build . -DCMAKE_BUILD_TYPE=$CONFIG