version: '{build}'

branches:
  except:
    - gh-pages

clone_folder: c:\projects\Qwt

image:
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013

configuration:
  #- Debug
  - Release

environment:
  matrix:
  - arch: Win32
    QWT_BUILD_SHARED_LIBS: ON
  - arch: Win64
    QWT_BUILD_SHARED_LIBS: ON
  - arch: Win32
    QWT_BUILD_SHARED_LIBS: OFF
  - arch: Win64
    QWT_BUILD_SHARED_LIBS: OFF

matrix:
  exclude:
    - arch: Win32
      image: Visual Studio 2017

init:
- echo %APPVEYOR_BUILD_WORKER_IMAGE% - %arch%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set vs=Visual Studio 15 2017)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set vs=Visual Studio 14 2015)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set vs=Visual Studio 12 2013)
- if "%arch%"=="Win64" ( set generator="%vs% Win64" )
- if "%arch%"=="Win32" ( set generator="%vs%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set qt5=C:\Qt\5.9\msvc2017)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set qt5=C:\Qt\5.9\msvc2015)
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set qt5=C:\Qt\5.6\msvc2013)
- if "%arch%"=="Win64" ( set qt5path="%qt5%_64" )
- if "%arch%"=="Win32" ( set qt5path="%qt5%" )
- echo %generator% - %qt5path%

before_build:
  - mkdir c:\projects\Qwt\build
  - cd c:\projects\Qwt\build
  - cmake --version
  - cmake .. -DCMAKE_BUILD_TYPE=%configuration% -G %generator% -DCMAKE_PREFIX_PATH=%qt5path% -DQWT_BUILD_SHARED_LIBS=%QWT_BUILD_SHARED_LIBS%

build_script:
  - cd c:\projects\Qwt\build
  - cmake --build . --config %configuration%
